services:

  db:
    container_name: fastify-db
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
