services:

  app:
    container_name: fastify-webapp
    build:
      context: .
      dockerfile: Dockerfile.app
    working_dir: /app
    environment:
      - PGHOST=fastify-db
      # NOTE: Playwrightで使用するブラウザを、node_modules配下にインストールさせる
      - PLAYWRIGHT_BROWSERS_PATH=0
    volumes:
      - ./e2e:/app/e2e
      - e2e_node_modules:/app/e2e/node_modules
      - node_modules:/app/node_modules
    tty: true
    depends_on:
      - db

volumes:
  e2e_node_modules:
  node_modules:
