services:

  app:
    container_name: fastify-webapp
    build:
      context: .
      dockerfile: Dockerfile.app
    working_dir: /app
    environment:
      - PGHOST=fastify-db
    volumes:
      - node_modules:/app/node_modules
    tty: true
    depends_on:
      - db

volumes:
  node_modules:
