name: Deploy to Production

run-name: Deploy to Production

on:
  workflow_run:
    workflows:
      - "Run E2E Test"
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Link to the environment
        run: railway environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}

      - name: Deploy
        run: railway up --ci --service fastify-webapp-sample
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
