name: Run E2E Test

run-name: Run E2E Test

on: push

jobs:
  run-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Playwright dependencies
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Setup E2E Test
        run: npm ci
        working-directory: ./e2e

      - name: Run E2E Test
        run: npm run test
        working-directory: ./e2e
        env:
          BASE_URL: "https://fastify-webapp-sample-staging-9128.up.railway.app"
          HEADLESS: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: e2e-allure-results
          path: e2e/allure-results
          retention-days: 1

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          pages: gh-pages

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: e2e-allure-results
          path: e2e/allure-results

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh-pages: gh-pages
          allure_results: e2e/allure-results  # このデータを基に、
          allure_history: allure-history      # このディレクトリにレポートを生成

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history         # レポートをGitHub Pagesへ配信
