name: Run Unit Test

run-name: Run Unit Test

on: push

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          key: node-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
          path: ${{ github.workspace }}/node_modules
          restore-keys: |
            node-${{ runner.os }}-

      - name: Setup Unit Test
        run: npm ci

      - name: Run Unit Test
        run: npm run test:ut
